---
- name: Install Apache Web Server
  apt: name=apache2 state=latest


- name: Generate INDEX.HTML file
  template: src=index.j2 dest={{ destin_file }}/index.html mode=0555
  notify: Restart Apache


- name: Start WebSerwer
  service: name=apache2 state=started enabled=yes
